#define HEIGHT_OF_ROW 8
#define NMBR_OF_ROWS 32
#define NUM_LEDS (HEIGHT_OF_ROW * NMBR_OF_ROWS)

// Fast LED
#define LED_PIN 14
#define MAX_BRIGHT 16
#define COLOR_ORDER GRB
#define FASTLED_ESP8266_RAW_PIN_ORDER
#define LED_TYPE WS2812
#define CLOCK_PIN 5